version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: |
            yarn install
            sudo apt-get install postgresql-client
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circle_test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml